### ISSUE TITLE
Version 0.18 KeyError: 'CORTEX_WORKERS_PER_REPLICA'

### ISSUE THREAD

**Issue by MrRace** [cortexlabs/cortex#1178] opened 2020-06-28 08:15 UTC
I install the new version 0.18. When run `cortex deploy` in my local machine, comes the error below:
```
Traceback (most recent call last):
  File "/src/cortex/serve/start_uvicorn.py", line 28, in <module>
    workers=int(os.environ["CORTEX_WORKERS_PER_REPLICA"]),
  File "/opt/conda/envs/env/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'CORTEX_WORKERS_PER_REPLICA'
```
What does it mean? What should I do to fix it? A lot of thanks!

**Comment by RobertLucian** [comment] 2020-06-28 11:38
@MrRace I cannot reproduce this with version 0.18 of the CLI and with the default images set. Therefore, I believe you must have used a different image for the `image` field in the `predictor` section. Version 0.18 has changed bits of the serving images, so if you use a custom version of the said images, then you'll have to rebuild them using version 0.18 as the base image.

Does this make sense? Waiting to see if this has been the issue for you.

**Comment by MrRace** [comment] 2020-06-28 11:42
@RobertLucian OK , I will try build a new IMAGE based on cortexlabs/python-predictor-cpu-slim:0.18.0. And try again, thanks for your prompt reply.

**Comment by MrRace** [comment] 2020-06-29 03:43
@RobertLucian It can work now!
In my local machine,  I  send concurrent requests to the server ,the server display message like `Service Unavailable POST` and `Exceeded concurrency limit.` By the way the stress test tool I used is `ab`, the command like：`ab -n 10000 -c 1000 -p single_task.json -T 'application/json' -r -k -s 120 http://localhost:8888/`. The result is:
```
Concurrency Level:      1000
Time taken for tests:   1.742 seconds
Complete requests:      10000
Failed requests:        5608
   (Connect: 0, Receive: 0, Length: 5608, Exceptions: 0)
Write errors:           0
Non-2xx responses:      5608
Keep-Alive requests:    0
Total transferred:      21738592 bytes
Total body sent:        2560000
HTML transferred:       20182584 bytes
Requests per second:    5740.69 [#/sec] (mean)
Time per request:       174.195 [ms] (mean)
Time per request:       0.174 [ms] (mean, across all concurrent requests)
Transfer rate:          12186.96 [Kbytes/sec] received
                        1435.17 kb/s sent
                        13622.14 kb/s total

```
We can see the number of `Failed requests` is too much. 
I set `threads_per_process : 4` and  `processes_per_replica : 8`.  Choose higher `processes_per_replica` sometimes seems work better,but it cost much more resources like memory and cpu. The `threads_per_process` seem no work when more concurrent requests come. I mean in my sense, more threads in a process can handle more requests, maybe it will cost more time(e.t. `Time per request` will higher). Therefore how and when should I set the value of  `threads_per_process`?

**Comment by RobertLucian** [comment] 2020-06-29 04:20
@MrRace that's really great! I'm delighted to hear it's working.

As for the error you are getting (`Service Unavailable POST` and `Exceeded concurrency limit`), that's because your throughput tester is exceeding the maximum number of in-flight requests the API can handle at any single point in time. Now, this maximum limit of which we are talking about `max_replica_concurrency` does not represent the maximum number of concurrent requests the API can immediately start processing, but the number of connections the API can hold concurrently. To avoid getting into this error again, just increase the value of `max_replica_concurrency` to something bigger - currently, it sits at 1024, so I may suggest you increase it to something more manageable, like 4096 or 8192. Bear in mind, there's a soft limit imposed by [Linux which is 65536](https://serverfault.com/a/769555). 

The downside to setting the concurrency limit to something higher is that if the cost of making a prediction is high enough, your API replica won't have enough compute power to keep up with your demand, which means, at some point (in seconds or minutes, depends on the traffic you get), your clients will start receiving 503s (aka `Service Unavailable POST` error), even if you've set the concurrency level at its highest. Setting `max_replica_concurrency` is generally set higher when you except to:
1. Have a high number of concurrent requests going on at any point in time and still be able to process them over time.
1. Or if you expect fair bursts of traffic and you need a buffer to prevent the service from retrieving 503s.

Also, it is generally recommended to set `processes_per_replica` to the number of cores you've got available for your API replica. To scale the number of permissible concurrent requests, only tweak `threads_per_processes`. The concurrency level you can achieve on your API replica is determined by `processes_per_replica * threads_per_processes`.

You can find out more here:
https://docs.cortex.dev/deployments/api-configuration

Let me know if there are any other lingering questions.

**Comment by MrRace** [comment] 2020-06-29 05:56
@RobertLucian  The `max_replica_concurrency` seems only for aws, how to modify the value in my local machine work?

**Comment by RobertLucian** [comment] 2020-06-29 08:22
@MrRace yes, you are correct. `max_replica_concurrency` is only available for AWS deployments. I have created ticket https://github.com/cortexlabs/cortex/issues/1182 to address this.

Until then, a workaround is to drop into the root directory of your project a `.env` file within which you can set the `CORTEX_MAX_REPLICA_CONCURRENCY` variable, which basically overrides the default value of the `max_replica_concurrency` field (currently sitting at 1024). The `.env` file could have the following content:
```bash
CORTEX_MAX_REPLICA_CONCURRENCY=4096
```

You can read more about the `.env` file here:
https://docs.cortex.dev/deployments/predictors#project-files

**Comment by MrRace** [comment] 2020-06-29 09:47
@RobertLucian  I have put a `.env` file(`CORTEX_MAX_REPLICA_CONCURRENCY=10000`) in the project directory, and restart the serving. However  `Exceeded concurrency limit` and `Service Unavailable POST` still happen.  My concurrency level is just  1000 and the total requests is 10000.  The `CORTEX_MAX_REPLICA_CONCURRENCY` setting seems not work？

**Comment by RobertLucian** [comment] 2020-06-29 16:58
@MrRace I looked through the source code and it appears a few things have changed. Therefore, the variables you have to tinker with are `CORTEX_MAX_PROCESS_CONCURRENCY` and `CORTEX_SO_MAX_CONN` and not `CORTEX_MAX_REPLICA_CONCURRENCY`, which was made redundant in one of the recent releases. Basically `CORTEX_MAX_PROCESS_CONCURRENCY` has been renamed to `CORTEX_SO_MAX_CONN`.

One thing to keep in mind is that when setting `CORTEX_MAX_PROCESS_CONCURRENCY`, you have to calculate it by taking `CORTEX_SO_MAX_CONN` and dividing it by the number of processes `processes_per_replica`. They are both integers.

Assuming you want to achieve a `max_replica_concurrency` of 10000 and you demand 4 `processes_per_replica`, you will set the following 2 variables in the `.env` file this way:
```bash
CORTEX_SO_MAX_CONN=10000
CORTEX_MAX_PROCESS_CONCURRENCY=2500
```

Does this make sense? Hopefully, it does. It can be a bit harder to get it since this is a workaround that tinkers with the internals of Cortex. With https://github.com/cortexlabs/cortex/issues/1182 solved, this workaround will no longer be required.

**Comment by RobertLucian** [comment] 2020-06-30 00:37
@MrRace just to be sure, I tried the above too (using my suggestions) on the [TensorFlow Iris example](https://github.com/cortexlabs/cortex/tree/master/examples/tensorflow/iris-classifier) with the same `ab` concurrency levels and the same number of samples.

Out of 10,000 samples, only 25 got 503s, which is 0.25%. Reducing the concurrency level down to 990 for the benchmarking program got me no 503s, which is really great! That 0.25% is a result of the uneven process of distributing requests to each worker - so one worker might temporarily get more requests than it can handle and thus, it may throw some 503s. That's why, internally, we are adding 100 to what the user sets for the `max_replica_concurrency` field in the `cortex.yaml` config - to account for those small imbalances.

**Comment by MrRace** [comment] 2020-06-30 02:37
@RobertLucian Thanks a lot! It can work now!

**Comment by deliahu** [comment] 2020-07-06 18:34
I'll go ahead and close this now, feel free to comment here or create a new issue if you run into any issues!

**Closed by deliahu** 2020-07-06 18:34 UTC
Labels: question
