### ISSUE TITLE
Shadow pipelines

### ISSUE THREAD

**Issue by vishalbollu** [cortexlabs/cortex#1932] opened 2021-03-03 13:47 UTC
Augment traffic splitter to add support for mirror [functionality](https://istio.io/latest/docs/tasks/traffic-management/mirroring/#mirroring-traffic-to-v2).

- [ ] Can you have multiple primaries and a shadow pipeline? What are the possible combinations of multiple primaries and shadow pipelines? Should we support all combinations or only a few to maintain a nice user experience?
- [ ] Add a field to indicate which branch will be the primary and which branch(es?) will be mirror
- [ ] Add validations for the designed UI
- [ ] Update telemetry and UserStr functions accordingly
- [ ] Update docs

**Comment by miguelvr** [comment] 2021-03-04 10:37
duplicate of #1889

**Closed** 2021-03-04 10:39 UTC
