### ISSUE TITLE
Improve status in cortex get

### ISSUE THREAD

**Issue by vishalbollu** [cortexlabs/cortex#429] opened 2019-09-05 21:44 UTC
### Description

The status of an API after deploying a failed update is `live` with up-to-date count as 0. It doesn't clearly state that the latest deployment has failed. The status messages can be improved to relay the message that is most important and relevant to the user.

**Comment by deliahu** [comment] 2019-09-05 21:47
In this case, the status should be "error"

Dupe of #408

**Closed by deliahu** 2019-09-05 21:47 UTC
Labels: enhancement
