### ISSUE TITLE
Discrepancy between the response code received by client and the response code recorded by websever 

### ISSUE THREAD

**Issue by vishalbollu** [cortexlabs/cortex#1306] opened 2020-08-26 16:50 UTC
#### Description

The response codes (200, 404 etc.) are recorded in the webserver currently. If the there is an error in the network (e.g. a timeout), the webserver may still record a 200 while the client may receive a 5XX response code. The output of `cortex get` may be misleading.

Should response codes be collected in multiple areas along the network? If yes, which metrics should be displayed in `cortex get`?

**Comment by deliahu** [comment] 2020-11-26 01:36
Duplicate of https://github.com/cortexlabs/cortex/issues/841 and https://github.com/cortexlabs/cortex/issues/1619

**Closed by deliahu** 2020-11-26 01:36 UTC
Labels: bug, enhancement
