### ISSUE TITLE
submitted the job request with "workers: 20" but only 5 spot instances are running

### ISSUE THREAD

**Issue by nellaG** [cortexlabs/cortex#1593] opened 2020-11-24 10:14 UTC
#### Version

0.22.1

#### Description
hello,
when I'm submitting the job request with `workers` value above 5, only 5 spot instances are running and remaining quantity of requested workers are in pending status. (e.g. when `workers` is 20, only 5 workers are running and 15 workers are pending)

I checked AWS EC2 spot worker autoscaling group via AWS console, when the job is submitted, the `desired capacity` is set to 5. (not 20)
#### Configuration

```
cortex.yaml
- name: 
  kind: BatchAPI
  predictor:
    type: python
    path: predictor.py
    image: cortexlabs/python-predictor-gpu:0.22.1
    env:
      ENV: aws
  compute:
    mem: 2G
    gpu: 1
```

```
cluster.yaml
instance_type: g4dn.xlarge
min_instances: 0
max_instances: 200
instance_volume_size: 30
instance_volume_type: gp2
spot: true
spot_config:
    instance_distribution: [g4dn.xlarge]
    on_demand_base_capacity: 1
    on_demand_percentage_above_base_capacity: 0
    on_demand_backup: true # recommended for production clusters
```
```
$ cortex cluster info
aws region:                                    ap-northeast-2
availability zones:                            [ap-northeast-2a, ap-northeast-2c]
instance type:                                 g4dn.xlarge
min instances:                                 0
max instances:                                200
use spot instances:                            yes
spot instance distribution:                    [g4dn.xlarge]
spot on demand base capacity:                  1
spot on demand percentage above base capacity: 0
spot instance pools:                           1
on demand backup:                              yes
```

#### Steps to reproduce

1. configure `max_instances` above 5
2. submit the job with `workers` above 5
3. get the job info with `cortex get {api_name} {job_id}`

#### Expected behavior

all of requested workers are should be `running`  concurrently

#### Actual behavior

only 5 workers are in running and remaining is `pending`

#### Screenshots

(optional)

#### Stack traces

(error output from `cortex logs <api name>`)

```text
<paste stack traces here>
```

#### Additional context

(optional)

#### Suggested solution

(optional)

**Comment by vishalbollu** [comment] 2020-11-24 16:40
Was your `max_instances` setting initially set to 5 and then you used the `cortex cluster configure` command to raise the `max_instances` to 200? If this is the case, then you've encountered the bug https://github.com/cortexlabs/cortex/issues/1567. This fix for this bug will in v0.23.

In the meantime, it would be great if you could spin up a new cluster using 0.22.1 with the min/max set to the desired values and try submitting the job again. Let us know how it goes.

**Comment by vishalbollu** [comment] 2020-11-24 20:20
Following up on this, the fix for the `cortex cluster configure` #1567 was included in the 0.22.1 patch release. So the previous scenario may not apply to you.

I tried to reproduce the issue but it worked as expected for me when I requested 10 workers, I immediately received 10 workers. Given that I can't reproduce the issue, it would be great if you could try to reproduce the issue again. When you do encounter the issue, run the command `cortex cluster info -c cluster.yaml --debug` to export information about the current state of your cluster to a zip file. You can email the zip file to me at vishal@cortexlabs.com so that investigate the issue in greater detail.

**Comment by nellaG** [comment] 2020-11-25 02:28
@vishalbollu Yes.`max_instances` of my cluster was set to 5 initially as you said, and after `max_instances` was set to 200 manually via AWS EC2 auto scaling group console. When I checked cluster info using `cortex cluster info` , I checked that `max_instances` was set to 200 correctly. Should I not have set the `max_instances` value using AWS Console?

**Comment by deliahu** [comment] 2020-11-25 04:50
@nellaG yes that is correct: because there are a few places where the max instances must be updated, it should be done via the cortex CLI. I don't think you'll have to spin down your cluster to fix it, you should be able to do one of the following:

If you have a [cluster configuration file](https://docs.cortex.dev/install#configure-cortex), update `max_instances` in the file, and run:

`cortex cluster configure --config cluster.yaml`

If you don't have a cluster configuration file, it will prompt you to specify max instances when you run:

`cortex cluster configure`

Let us know if that resolves it for you!

**Comment by nellaG** [comment] 2020-11-25 07:03
@deliahu   I just updated `max_instances` value using `cortex cluster configure` command, and now everything works fine. Thanks for your help!

**Comment by RobertLucian** [comment] 2020-11-25 14:41
@nellaG that's awesome! Let us know if you have any other questions/issues down the line. In the meantime, I'll close this ticket.

**Closed by RobertLucian** 2020-11-25 14:41 UTC
Labels: bug
