### ISSUE TITLE
Allow ELB to select instance based on model loaded in memory

### ISSUE THREAD

**Issue by lminer** [cortexlabs/cortex#1873] opened 2021-02-07 23:05 UTC
It would be nice if, when receiving a request, the ELB tried to route the request to a server that already has a model in memory.

I'm currently using a multi-model predictor with six separate models. There is a 10 second cost to load a model into memory. Even though I have 6 servers running simultaneously, I always incur the 10 second expense, because the ELB doesn't know that it should favor the instance that already has the requested model loaded in memory.

**Comment by RobertLucian** [comment] 2021-02-07 23:19
Are you using the multi-model caching functionality?

**Comment by lminer** [comment] 2021-02-07 23:21
Yeah. If I request the same model repeatedly, I don't see the 10 second switching cost.

**Comment by lminer** [comment] 2021-02-08 05:27
Here's my `cortex.yaml`

```
- name: foo
  kind: RealtimeAPI
  predictor:
    type: tensorflow
    path: foo/cortex_server.py
    models:
      paths:
        - foo
      cache_size: 1
      disk_cache_size: 6
    processes_per_replica: 1
    threads_per_process: 1
    image: quay.io/cortexlabs/tensorflow-predictor:0.27.0
    tensorflow_serving_image: quay.io/cortexlabs/tensorflow-serving-gpu:0.27.0
  compute:
    gpu: 1
  autoscaling:
    min_replicas: 6
    max_replicas: 6
```

**Comment by deliahu** [comment] 2021-02-08 05:30
@lminer Yes that is a good idea for a feature, and not something we currently support. If I understand correctly, is this ticket the same as your request? https://github.com/cortexlabs/cortex/issues/1828

Also, in this case, if you have 6 models and 6 replicas, is it possible for you to split it into 6 separate APIs?

**Comment by lminer** [comment] 2021-02-08 05:45
Yes. That's the one!

I could split it into 6 separate APIs and may end up doing that. It's just more expensive/complex.

**Comment by deliahu** [comment] 2021-02-08 06:05
Splitting it will only be more expensive if you plan on having fewer instances than models (otherwise it should be the same). Yes, it is a bit more complex if you split them. However the simplicity on the infrastructure side can have some advantages too (such as independent autoscaling, monitoring, etc for each API)

**Comment by deliahu** [comment] 2021-02-17 06:02
I'm gonna go ahead and close this ticket since I believe it's a duplicate of https://github.com/cortexlabs/cortex/issues/1828

**Closed by deliahu** 2021-02-17 06:02 UTC
Labels: enhancement
