### ISSUE TITLE
CLI Unexpected response from operator (status code 405)

### ISSUE THREAD

**Issue by RobertLucian** [cortexlabs/cortex#1341] opened 2020-09-07 21:51 UTC
#### Version

Noticed this on `0.18.1` and `0.19.0`.

#### Description

When `cortex deploy`ing, there are situations when `error: Unexpected response from operator (status code 405)` is returned instead of actually deploying the API. 

#### Steps to reproduce

There are no exact steps to reproduce yet. Just that it seems to occur when `cortex deploy -e aws` is run. As reported by @balakrishna222111.

**Comment by Mahi-debug** [comment] 2020-09-08 04:51
This error is also returned when we try it with cortex version 0.17.1 
Command: `cortex deploy --env aws`
Error: **error: unexpected response from operator (status code 405):**

**Comment by deliahu** [comment] 2020-09-08 15:32
@Mahi-debug thank you for the info.

Since we haven't been able to reproduce this yet, the next time that you see this error, do you mind sending us an email to dev@cortex.dev which includes the following information?

* The zip file generated by `cortex cluster info --debug`
* Your cluster.yaml` config (please hide or omit any AWS credentials)
* Your `cortex.yaml` config

**Comment by Mahi-debug** [comment] 2020-09-14 05:29
Thank you @deliahu for your response. I have shared the details at dev@cortex.dev. Hope to hear from you guys soon

**Comment by deliahu** [comment] 2020-09-14 16:47
@Mahi-debug thank you. Were you observing the 405s at the time you created the cluster info zip file? Also, does the request fail 100% of the time or is it intermittent?

**Comment by deliahu** [comment] 2020-09-14 16:51
@Mahi-debug Also, do you have a `cluster.yaml` file, or did you create your cluster without it (answering the cli prompts instead)?

**Comment by deliahu** [comment] 2020-09-14 21:51
@Mahi-debug I have one more question: Do you mind sending the output of `cortex version`, `cortex cluster info`, and `cortex env list`?

**Comment by Mahi-debug** [comment] 2020-09-23 06:29
> @Mahi-debug thank you. Were you observing the 405s at the time you created the cluster info zip file? Also, does the request fail 100% of the time or is it intermittent?

yes it fails 100% of the time

**Comment by deliahu** [comment] 2020-10-29 18:17
@balakrishna222111 @Mahi-debug I wanted to follow up on this: we didn't see any obvious issues in the information that you sent, and we have tried and been unable to reproduce it.

Are you still seeing `error: Unexpected response from operator (status code 405)`? If it's still a problem for you, do you mind trying on the latest release (0.21)?

**Comment by deliahu** [comment] 2020-11-26 21:43
@balakrishna222111 @Mahi-debug I'll go ahead and close this issue since we have improved the networking stack in recent releases. Feel free to reach out if you encounter this problem again!

**Closed by deliahu** 2020-11-26 21:43 UTC
Labels: bug
