### ISSUE TITLE
Make the requirements.txt / conda-packages.txt dependency files configurable

### ISSUE THREAD

**Issue by RobertLucian** [cortexlabs/cortex#1191] opened 2020-06-30 19:23 UTC
#### Description

Instead of installing pip/conda packages from the default `requirements.txt`/`conda-packages.txt` files, make it such that the user can configure them:

```yaml
- name: api
  kind: SyncAPI
  predictor:
    type: tensorflow
    dependencies:
      pip: alternative-requirements.txt
      conda: alternative-conda-packages.txt
```

#### Motivation

In case the user is already using these dependency files for another application that resides in the same directory as the Cortex project.

**Comment by deliahu** [comment] 2021-01-13 00:27
Duplicate of https://github.com/cortexlabs/cortex/issues/1777

**Closed by deliahu** 2021-01-13 00:27 UTC
Labels: enhancement
