### ISSUE TITLE
Is there a way to speed-up API deployment

### ISSUE THREAD

**Issue by imagine3D-ai** [cortexlabs/cortex#1827] opened 2021-01-25 18:39 UTC
When deploying an API and observing logs, it seems that the most time-consuming part of deployment is:

```
2021-01-25 18:37:27.401057:cortex:pid-1:INFO:downloading the project code
2021-01-25 18:37:27.483562:cortex:pid-1:INFO:downloading the python serving image
```

Is there a way to somehow make deploying an API quicker?

**Comment by deliahu** [comment] 2021-01-26 05:59
"downloading the python serving image" refers to downloading the docker image for the API.

By default, the image is hosted on quay.io, and likely has dependencies installed which you do not need. So, the best way to speed this up is to make the image smaller, and host the image on ECR in the same region as your cluster (assuming you're running on AWS). Here is our documentation for both of these approaches: https://docs.cortex.dev/workloads/managing-dependencies/images

**Comment by imagine3D-ai** [comment] 2021-01-28 09:57
@deliahu Is there an option to make a custom code changes to the slim python predictor image? I would like to change the `predict()` and `post_predict()` function to accomodate for my application

**Comment by miguelvr** [comment] 2021-01-28 10:14
> @deliahu Is there an option to make custom code changes to the slim python predictor image? I would like to change the `predict()` and `post_predict()` functions to accommodate for my application

the `predict` and `post_predict` can be defined in the predictor.py, which will be loaded in the docker image, just as before.

To speed up the deployment you can do one of these options:

**Option 1** - Easiest option
1. Change to the slim image in your `cortex.yaml` by setting the `image` field.
2. Implement the predictor just as before

**Option 2** - Most optimized option
1. Create a custom docker image, by starting from the cortex slim image (as described in the [docs](https://docs.cortex.dev/workloads/managing-dependencies/images)) and add the dependencies your predictor needs to start-up (e.g. install the pip packages).
2. Host your image in a container registry of your choice
3. Set the custom image in the `image` field in your `cortex.yaml`
4. Implement the predictor just as before

Bear in mind that the start-up time of an API depends on different factors:
1. Size of the docker image that needs to be downloaded
2. Time that it takes to download and install the python dependencies
3. Time that takes to download your model

All of the above depend on the internet connection and therefore having everything running in the same region and zone, minimizes the download speeds

**Comment by imagine3D-ai** [comment] 2021-01-28 10:34
I have a question about aws regions: as I understand, the regions for all the aws services, need to be the same to maximize performance, but what does that mean for the users outside of the regions where services are located? If I'm in Europe and use the service which is hosted in `us-east-2`, will the perfomance I get be slower or will there be any additional charges?

**Comment by miguelvr** [comment] 2021-01-28 10:38
> If I'm in Europe and use the service which is hosted in `us-east-2`, will the perfomance I get be slower?

the latency will be larger if you are making requests across zones.

> or will there be any additional charges?

you might have data transfer charges from AWS, depending on what you are doing.

**Comment by imagine3D-ai** [comment] 2021-01-28 10:41
If I have an EC2 instance running in `us-east-2`, which downloads the data from ECR located in the same region and I myself am in Europe and use that EC2 instance, will I get additional data transfer charges?

**Comment by miguelvr** [comment] 2021-01-28 10:42
> If I have an EC2 instance running in `us-east-2`, which downloads the data from ECR located in the same region and I myself am in Europe and use that EC2 instance, will I get additional data transfer charges?

I don't think so, because the data is transferred within the same zone. You may want to check AWS docs on that

**Comment by miguelvr** [comment] 2021-01-28 11:07
closing this issue, as I think the question was answered already

**Closed by miguelvr** 2021-01-28 11:07 UTC
Labels: question

**Comment by imagine3D-ai** [comment] 2021-01-28 14:07
I noticed when watching the logs that the most time-consuming part of launching an API is actually when it is in the `fetching logs...` state. 

`fetching logs..` takes about 2 minutes and downloading the image and the model takes about 1-1.5 minutes (after moving the image to ECR in the same region, as @deliahu suggested). Is there a way to reduce the time the API spends in `fetching logs` state when launching?

**Comment by miguelvr** [comment] 2021-01-28 14:09
cc @vishalbollu

**Comment by vishalbollu** [comment] 2021-01-28 14:40
In the latest version of cortex this message has been updated to `waiting for replica/worker to initialize ...` to help reduce the confusion. Your API is not waiting to fetch the logs, your `cortex logs` command is waiting for a replica or worker to become ready before logs can be streamed to your terminal.

The underlying reason for why you see `fetching logs...` for a long period of team is because your API replicas are taking a while to initialize. The main reason why you might have to wait 1 to 2 minutes before a replica can initialize is because your cluster is autoscaling up and it takes that long to get a new EC2 instance from AWS. You can minimize this by configuring your cluster's `min_instances` to be non-zero (or enough to avoid scale-ups on initial deploys). 

There is a tradeoff between speeding up the initial api time and the cost of maintaining a minimum number of EC2 instances.

**Comment by imagine3D-ai** [comment] 2021-01-28 14:57
I also noticed that sometimes it’s possible for a cluster to get a new EC2 instance very quickly (less than 30 seconds). I was wondering if it is possible to replicated that behaviour

**Comment by vishalbollu** [comment] 2021-01-28 22:32
Perhaps It takes longer for an instance to spin up if the autoscaling group (the cluster's workers nodes) already has instances. Or maybe on demand instances spin up faster than spot instances? Unfortunately, I don't have any more insight into this. At this point I believe we rely on AWS's ability to provision instances and add them to the cluster. If you do notice any reproducible patterns, please let us know.
