### ISSUE TITLE
Add OpenAPI docs / UI to RealtimeAPI

### ISSUE THREAD

**Issue by miguelvr** [cortexlabs/cortex#2017] opened 2021-03-30 10:42 UTC
### Description

Add OpenAPI 3.0 docs on a pre-defined route (e.g. `/docs`) for the RealtimeAPI kind.

### Motivation

OpenAPI docs are a useful tool to self-document an API when you have external users hitting your API.

### Additional context

FastAPI provides this out of the box, so it can be potentially easy to implement.

**Comment by deliahu** [comment] 2021-04-14 23:03
Duplicate of #1318

**Closed by deliahu** 2021-04-14 23:03 UTC
Labels: RealtimeAPI, enhancement
