### ISSUE TITLE
Support metrics tracking for responses with multiple predictions

### ISSUE THREAD

**Issue by ospillinger** [cortexlabs/cortex#621] opened 2019-12-02 20:10 UTC
### Description

Trackers should correctly manage metrics collection when there are multiple samples in one request.

### Motivation

Improve support for users who are running batch prediction APIs.

**Comment by deliahu** [comment] 2020-11-26 05:09
Duplicate of https://github.com/cortexlabs/cortex/issues/1215

**Closed by deliahu** 2020-11-26 05:09 UTC
Labels: enhancement
