### ISSUE TITLE
Document how to access statsd client

### ISSUE THREAD

**Issue by vishalbollu** [cortexlabs/cortex#1249] opened 2020-08-01 19:21 UTC
#### Description

Create a guide on how to access to statsd client to enable users to send custom metrics using Cortex's metrics infrastructure.

Sample predictor may look like this:

```
import datadog


class PythonPredictor:
    def __init__(self, config):
        ...

    def predict(self, payload):
        datadog.statsd.increment("language_identifier", value=1, tags=["dimension_name1:dimension_value", "dimension_name2:dimension_value"])
```

**Comment by deliahu** [comment] 2020-11-26 05:15
duplicate of https://github.com/cortexlabs/cortex/issues/1215

**Closed by deliahu** 2020-11-26 05:15 UTC
Labels: docs
