### ISSUE TITLE
Don't save model metadata in API spec

### ISSUE THREAD

**Issue by vishalbollu** [cortexlabs/cortex#1549] opened 2020-11-10 19:06 UTC
#### Description

A list of model metadata (`CuratedModelResources`) is collected during validations. This list is currently attached to the API spec. The list doesn't need to be attached to the API spec because the model metadata is regenerated by each replica. The list can also become very large depending on the number of models and model versions in the directory.

**Comment by deliahu** [comment] 2020-11-25 22:44
Duplicate of https://github.com/cortexlabs/cortex/issues/1596

**Closed by deliahu** 2020-11-25 22:44 UTC
Labels: enhancement, refactor
