### ISSUE TITLE
Deploy a CLI executable controlled with python

### ISSUE THREAD

**Issue by Magdiel3** [cortexlabs/cortex#1140] opened 2020-06-18 21:24 UTC
I am developing a NLP project with [StarSpace](https://github.com/facebookresearch/StarSpace) and would like to deploy it for production with Cortex. Currently, I'm running a python script that starts a task in CLI (using [pexpect](https://github.com/pexpect/pexpect)) and I'm able to leave that running and just call a predict function which sends my input to the application and listens to the output. 

When I try to make the deployment locally, I always get an error `ERROR:failed to start api` and `OSError: [Errno 8] Exec format error` which are the direct cause of `cortex.lib.exceptions.UserRuntimeException: error: pexpect_test.py: __init__: [Errno 8] Exec format error: runtime exception`. I have the executable in the same root as my cortex.yaml and as well, all the required files.

The `cortext.yaml` is:

```
- name: trainmode2-predict
  predictor:
    type: python
    path: pexpect_test.py
  compute:
    mem: 8G
```

Is it possible, somehow to get it running? And, later on, deploy with aws? Can anyone suggest me any other more efficient apporach for these?

**Comment by RobertLucian** [comment] 2020-06-18 21:40
@Magdiel3 I think that might be because the shebang hasn't been set for your executable script (which I assume it's a script from what I can tell) or if you haven't added the `/bin/bash` shell to your command.

There's already a way to execute scripts and that's by adding a script called `dependencies.sh` to the root directory of your Cortex project. That script is spawned with the `/bin/bash` shell, so there's no need for you to add the shebang. The documentation for this can be found at https://docs.cortex.dev/deployments/system-packages#bash-script.

Also, if this isn't what you're looking for, could you then share more about your `pexpect_test.py` script? I could have a look at it and see what's wrong with it. If this is confidential, I could jump on a call or you could email me the specifics at robert.lucian.chiriac@gmail.com.

**Comment by Magdiel3** [comment] 2020-06-18 22:04
What I'm doing is starting the application within the python script (when `__init__` is called) and then just input and listen with the `predict` function.

I have not tried to start the application from dependencies.sh and then just keep listening, which I'm not sure how I could do that. Here it is how the `pexpect_test.py`:

```
import pexpect

class PythonPredictor:
    def __init__(self,config):
        print("getting it to run")
        child = pexpect.spawn("./query_predict_placement_id models/tab_separated_descriptions_spaced_v02_extended 300 datasets/tab_separated_descriptions_spaced_v02_extended.txt datasets/labels_for_tab_separated_descriptions_spaced_v02_extended.txt 9086",timeout=5)
        child.expect("STARSPACE-2018-2")
        # print(child.before.decode("utf-8"))
        child.expect(".*Enter some text:")
        # print(child.before)
        self.child = child
        print("Succesfully initialized")

    def predict(self,payload):
        print(f"Getting predictions for {payload}")
        self.child.sendline(payload)
        self.child.expect(payload)
        self.child.expect(f"Enter some text:")
        output = self.child.before.decode("utf-8")
        # print(output)
        return output
```

I'm running an executable compiled with make on my local machine. And also, it's just one application that I'm running and want to keep it running and serving. The loading of the model (the command that I'm spawning) takes arround 7 to 8 min to start listening for an input. I really appreciate the intention of a call, and maybe my goal is not very suited for cortex, but I find it super cool to just deploy and serve which such an ease.

**Comment by Magdiel3** [comment] 2020-06-18 22:09
What I'm doing is starting the application within the python script (when `__init__` is called) and then just input and listen with the `predict` function.

I have not tried to start the application from dependencies.sh and then just keep listening, which I'm not sure how I could do that. Here it is how the `pexpect_test.py`:

```
import pexpect

class PythonPredictor:
    def __init__(self,config):
        print("getting it to run")
        child = pexpect.spawn("./query_predict_placement_id models/model_v02 300 datasets/dataset_extended.txt datasets/labels.txt 9086",timeout=600)
        child.expect("STARSPACE-2018-2")
        # print(child.before.decode("utf-8"))
        child.expect(".*Enter some text:")
        # print(child.before)
        self.child = child
        print("Succesfully initialized")

    def predict(self,payload):
        print(f"Getting predictions for {payload}")
        self.child.sendline(payload)
        self.child.expect(payload)
        self.child.expect(f"Enter some text:")
        output = self.child.before.decode("utf-8")
        # print(output)
        return output
```

I'm running an executable compiled with make on my local machine. And also, it's just one application that I'm running and want to keep it running and serving. The loading of the model (the command that I'm spawning) takes arround 7 to 8 min to start listening for an input. I really appreciate the intention of a call, and maybe my goal is not very suited for cortex, but I find it super cool to just deploy and serve which such an ease.

**Comment by RobertLucian** [comment] 2020-06-18 23:03
@Magdiel3 thank you for coming back with more information. Your goal appears to be suited for cortex, after all, you're trying to make predictions, so let's see how we can fix this for you.

I see that this is failing at

```python
child = pexpect.spawn("./query_predict_placement_id models/model_v02 300 datasets/dataset_extended.txt datasets/labels.txt 9086",timeout=600)
```

Could you change that to:

```python
child = pexpect.spawn("/bin/bash ./query_predict_placement_id models/model_v02 300 datasets/dataset_extended.txt datasets/labels.txt 9086",timeout=600)
```

And then see if this working?

If this isn't working, could you share your environment with us? This is for the purpose of reproducing your error and then finding a solution.

**Comment by Magdiel3** [comment] 2020-06-19 11:45
@RobertLucian I have already tried with the `/bin/bash` but still dows'nt works. Now I'm getting an error at the execution of the CLI command:
```
./query_predict_placement_id: ./query_predict_placement_id: cannot execute binary file
```

So basically my goal is to run the c++ application (compiled in my machine as specified [here](https://github.com/facebookresearch/StarSpace/tree/master/python#how-to-build) and all my documents are in the same directory as well

**Comment by vishalbollu** [comment] 2020-06-19 14:39
@Magdiel3  Is it possible that your binary is compiled on an architecture that is different from the run time. What OS is running on your machine? The Docker runtime is Linux based. If you compiled your binary on Mac OSX, you may run into issues.

To be completely safe, instead of compiling the binary on your machine, you can try compiling it in the Dockerfile to ensure that the binary is compatible with the Docker runtime.

You can find the instructions for creating your own Dockerfile here: https://docs.cortex.dev/deployments/system-packages#custom-docker-image

As a rough starting point:
```
FROM cortexlabs/python-predictor-cpu-slim:<your cortex version>

RUN <install additional binaries such as cmake and make to compile the library>

RUN git clone https://github.com/facebookresearch/StarSpace

RUN cd StarSpace/python && make
```

**Comment by Magdiel3** [comment] 2020-06-20 15:16
@vishalbollu Indeed I was working with a binary compiled for Mac OSX. I get the idea of compiling in the Dockerfile and appreciate the help for starting the Dockerfile. I have not yet been able to make it work as I'm new with Docker images and I am not sure how to download and place [Boost](https://www.boost.org/) which is another requirement for Starspace as described [here](https://github.com/facebookresearch/StarSpace#requirements).

**Comment by vishalbollu** [comment] 2020-06-20 16:15
@Magdiel3 I found the installation instructions for Boost in the [Starspace readme](https://github.com/facebookresearch/StarSpace#requirements).

We can add the instructions to install boost in the Dockerfile. It looks like we need wget to download boost so for ease of use let's install wget as well. Your Dockerfile might look something like this:

```
FROM cortexlabs/python-predictor-cpu-slim:<your cortex version>

RUN <install libraries such as cmake and make to compile the library>

# install wget
RUN apt-get update \
  && apt-get install -y wget

# download boost
RUN wget https://dl.bintray.com/boostorg/release/1.63.0/source/boost_1_63_0.zip \
  && unzip boost_1_63_0.zip \
  && mv boost_1_63_0 /usr/local/bin

RUN git clone https://github.com/facebookresearch/StarSpace

RUN cd StarSpace/python && ./build.sh
...
```

**Comment by Magdiel3** [comment] 2020-06-22 13:43
Thanks for all the help. Everything seems to be working locally. There was just an issue with trying to use the local Docker image and got this error: 

```
error: ...: image: docker_images/starspace_image is not accessible
Error response from daemon: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```

The `cortex.yaml` contained  
```
predictor:
    type: python
    path: pexpect_test.py
    image: docker_images/starspace_image:v1
```

How we managed to work that out was using DockerHub and updating the `cortex.yaml` to:
```
  predictor:
    type: python
    path: pexpect_test.py
    image: magdiel3/recommender-cortex:v1
```

As I read from [this comment](https://github.com/cortexlabs/cortex/issues/1094#issuecomment-640693855) on #1094, there will be support for using local images then v0.18 is released, isn't it?

**Comment by RobertLucian** [comment] 2020-06-22 14:18
@Magdiel3 yes, that's correct. v0.18 will support local images for local Cortex deployments.

**Comment by deliahu** [comment] 2020-06-25 17:44
@Magdiel3 v0.18 has now been released, which supports local images (here is the full [changelog](https://github.com/cortexlabs/cortex/releases/tag/v0.18.0)).

I'll go ahead and close this issue, feel free to reach out if you have additional questions!

**Closed by deliahu** 2020-06-25 17:44 UTC
Labels: question
