### ISSUE TITLE
Allow updating the instance volume size for an existing cluster

### ISSUE THREAD

**Issue by RobertLucian** [cortexlabs/cortex#1246] opened 2020-07-31 18:21 UTC
#### Description

Allow updating the instance volume size `instance_volume_size` in `cluster.yaml` after the cluster has already been spun up. Exactly like it's the case for `min_instances`/`max_instances`.

#### Motivation

Maybe the user's requirements when it comes to the required disk space have changed and the user doesn't want to spin down a cluster and then bring up another one with different volume sizes. That can be costly.

#### Debatable points

1. When the `instance_volume_size` field is updated, what do we do about the running APIs / instances?
1. Do we employ a rolling-update strategy, where the instances are gradually replaced with those that have more/less disk space? We would also have to prevent any downtime with APIs while they are being transitioned to the other instances.
1. If the user updates `instance_volume_size` to a higher value, can we just increase each of the running instances' volume size on the fly?

**Comment by deliahu** [comment] 2020-11-25 17:31
duplicate of https://github.com/cortexlabs/cortex/issues/529

**Closed by deliahu** 2020-11-25 17:31 UTC
Labels: enhancement
